nome = str(input('Digite seu nome completo: ')).strip()
print('Analizando seu nome...')
print('Seu nome completo é', nome)
print('Seu nome em letras maúsculas é {}'.format(nome.upper()))
print('Seu nome em letras minúsculas é {}'.format(nome.lower()))
print('O seu nome é {} e tem ao todo {} letras'.format(nome, len(nome) - nome.count(' ')))
#print('Seu primeiro nome tem {} letras'.format(nome.find(' ')))
separar = nome.split()
print('Seu primeiro nome é {} e tem {} letras'.format(separar[0], len(separar[0])))